name: Portfolio CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Java
        run: java -version

      - name: Check Backend Folder
        run: |
          Get-Location
          Get-ChildItem
          Get-ChildItem .\backend

      - name: Check Maven Wrapper
        run: |
          cd backend
          .\mvnw.cmd -version

      - name: Build Backend
        run: |
          cd backend
          .\mvnw.cmd clean package -DskipTests